# Copyright (c) 2015 Hewlett-Packard Development Company, L.P.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
- name: Install dependencies
  package:
    name: git

- name: ensure installation root folder exists
  become: yes
  file:
    state: directory
    dest: "{{ git_root }}"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"

- name: "Download via GIT"
  git:
    dest: "{{ item.git_folder }}"
    force: "{{ force_update_repos | bool }}"
    repo: "{{ item.git_url }}"
    version: "{{ item.git_branch }}"
    update: "{{ update_repos | bool }}"
    clone: yes
  loop: "{{ bifrost_install_sources }}"
  when:
    - not copy_from_local_path | bool
    - item.source_install | default(true) | bool
    - item.enabled | default(true) | bool

- name: "Ensure ownership of repositories"
  file:
    path: "{{ item.git_folder }}"
    owner: "{{ ansible_env.SUDO_USER | default(ansible_user_id) }}"
    group: "{{ ansible_user_gid }}"
    recurse: yes
  loop: "{{ bifrost_install_sources }}"
  when:
    - not copy_from_local_path | bool
    - item.source_install | default(true) | bool
    - item.enabled | default(true) | bool

- name: "Purge existing path when copying"
  file:
    path: "{{ item.git_folder }}"
    state: absent
  loop: "{{ bifrost_install_sources }}"
  when:
    - copy_from_local_path | bool
    - item.source_install | default(true) | bool
    - item.enabled | default(true) | bool
    - update_repos | bool

- name: "Copy from local path"
  copy:
    src: "{{ item.git_url }}/"
    dest: "{{ item.git_folder }}/"
    remote_src: yes
    force: "{{ update_repos | bool }}"
    owner: "{{ ansible_env.SUDO_USER | default(ansible_user_id) }}"
    group: "{{ ansible_user_gid }}"
  loop: "{{ bifrost_install_sources }}"
  when:
    - copy_from_local_path | bool
    - item.source_install | default(true) | bool
    - item.enabled | default(true) | bool
