# Copyright (c) 2015 Hewlett-Packard Development Company, L.P.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
- name: "Collect facts"
  setup:
    gather_timeout: "{{ fact_gather_timeout }}"

- import_role:
    name: bifrost-cloud-config

- name: "Setup DHCP for nodes."
  template:
    src: dhcp-host.j2
    dest: "/etc/dnsmasq.d/bifrost.dhcp-hosts.d/{{ inventory_hostname }}"
    owner: root
    group: root
    mode: 0644
  when: inventory_dhcp | bool
  become: yes
- name: "Setup DNS address for nodes."
  template:
    src: dns-address.j2
    dest: "/etc/dnsmasq.d/host_record_{{ inventory_hostname }}"
    owner: root
    group: root
    mode: 0644
  when: inventory_dns | bool
  become: yes
- name: "Sending dnsmasq HUP"
  # Note(TheJulia): We need to actually to send a hup signal directly as
  # Ansible's reloaded state does not pass through to the init script.
  command: killall -HUP dnsmasq
  become: yes
  when: inventory_dhcp | bool or inventory_dns | bool

- name: "Execute node introspection"
  openstack.cloud.baremetal_inspect:
    cloud: "{{ cloud_name | default(omit) }}"
    auth_type: "{{ auth_type | default(omit) }}"
    auth: "{{ auth | default(omit) }}"
    ca_cert: "{{ tls_certificate_path | default(omit) }}"
    uuid: "{{ uuid | default('') }}"
    name: "{{ name | default('') }}"
    timeout: "{{ inspection_wait_timeout }}"
