- hosts: all
  tasks:
    - command: git checkout {{ upgrade_from }}
      args:
        chdir: "{{ ansible_user_dir }}/{{ item.src_dir }}"
      loop: "{{ zuul.projects.values() | list }}"
      when: item.name not in skip_upgrade
    - shell:
        cmd: |
          set -eo pipefail
          ./scripts/test-bifrost.sh 2>&1 | tee "{{ ansible_user_dir }}/bifrost-old.log"
        chdir: "{{ ansible_user_dir }}/{{ zuul.projects['opendev.org/openstack/bifrost'].src_dir }}"
        executable: /bin/bash
      environment:
        BIFROST_TRACE: "true"
        ENABLE_KEYSTONE: "{{ enable_keystone | default(false) | bool | lower }}"
        LOG_LOCATION: "{{ ansible_user_dir }}/logs"
        UPPER_CONSTRAINTS_FILE: "{{ ansible_user_dir }}/{{ zuul.projects['opendev.org/openstack/requirements'].src_dir }}/upper-constraints.txt"
        WORKSPACE: "{{ ansible_user_dir }}/src/opendev.org"
        ZUUL_BRANCH: "{{ upgrade_from }}"
    - command: git checkout --force -
      args:
        chdir: "{{ ansible_user_dir }}/{{ item.src_dir }}"
      loop: "{{ zuul.projects.values() | list }}"
      when: item.name not in skip_upgrade
    - shell:
        cmd: |
          set -eo pipefail
          ./scripts/test-bifrost.sh 2>&1 | tee "{{ ansible_user_dir }}/bifrost-new.log"
        chdir: "{{ ansible_user_dir }}/{{ zuul.projects['opendev.org/openstack/bifrost'].src_dir }}"
        executable: /bin/bash
      environment:
        BIFROST_TRACE: "true"
        ENABLE_KEYSTONE: "{{ enable_keystone | default(false) | bool | lower }}"
        LOG_LOCATION: "{{ ansible_user_dir }}/logs"
        UPPER_CONSTRAINTS_FILE: "{{ ansible_user_dir }}/{{ zuul.projects['opendev.org/openstack/requirements'].src_dir }}/upper-constraints.txt"
        WORKSPACE: "{{ ansible_user_dir }}/src/opendev.org"
        ZUUL_BRANCH: "{{ zuul.branch }}"
