---
# Ensure that Ansible is using python interpreter and dependencies inside the bifrost virtual environment
bifrost_venv_dir: "{{ lookup('env', 'VENV') or '/opt/stack/bifrost' }}"
ansible_python_interpreter: "{{ bifrost_venv_dir + '/bin/python3' }}"

noauth_mode: false

network_interface: "virbr0"
ans_network_interface: "{{ network_interface | replace('-', '_') }}"
# NOTE(dtantsur): dynamic playbooks are run on bare metal hosts, not on
# localhost, and the interface fact may not be available for them.
ans_interface_host: "{{ groups['target'][0] if 'target' in groups else '127.0.0.1' }}"
internal_ip: "{{ hostvars[ans_interface_host]['ansible_' + ans_network_interface]['ipv4']['address'] }}"

enable_tls: false
api_protocol: "{{ 'https' if enable_tls | bool else 'http' }}"
ironic_api_url: "{{ api_protocol }}://{{ internal_ip }}:6385"
